name: Gradle CI

on:
  workflow_dispatch:
  push:
  pull_request:
  release:
    types: [created, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout ModMail
        uses: actions/checkout@v7
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        run: ./gradlew clean shadowJar --parallel
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}

      - name: Stage jar for Actions
        if: ${{ github.event_name != 'release' }}
        run: mkdir staging && cp build/libs/ModMail.jar staging && mv staging/ModMail.jar staging/ModMail_$GITHUB_SHA.jar
      - name: Upload jar to Actions
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v7
        with:
          name: ModMail_Dev-Build
          path: staging/ModMail_*.jar

      - name: Stage jar for Release
        if: ${{ github.event_name == 'release' }}
        run: mkdir staging && cp build/libs/ModMail.jar staging && mv staging/ModMail.jar staging/ModMail_${{ github.event.release.tag_name }}.jar
      - name: Upload jar to Release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v3
        with:
          files: staging/ModMail_${{ github.event.release.tag_name }}.jar
          tag_name: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: build
    if: ${{ github.event_name == 'release' }}
    uses: ./.github/workflows/docker.yaml
    with:
      release_version: ${{ github.event.release.tag_name }}
    permissions:
      contents: read
      packages: write
